import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CriptoTheme } from "./components/CriptoTheme";

import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InvestiFi Frontend Coding Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-full bg-white dark:bg-slate-900`}
      >
       <CriptoTheme>{children}</CriptoTheme>
      </body>
    </html>
  );
}
